### ISSUE TITLE
Sequence reader script

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/Finkle-PHYS-479#1]
Throughout the project, we will need to convert the given phosphorylation sites into sequences around that site, with a fixed length.

For instance, when we see "RTN4 site S107", (assuming we are using a window of plus minus 5) we need to convert it to the sequence PERQPSWDPSP. The center S here is the phosphorylated residue and the other letters are amino acids surrounding it. Full sequences are provided by the UniProt database at ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz.

Write a script that will make this conversion. It will take the gene name, the location, and the window size, and it will return the sequence as a string.

There are cases where returning this sequence is not possible. In such cases, let the script return a null value.

**Comment by nurith** [comment]
Adam, There are a lot of packages that deal with sequences. You should 
probably look them up.

Thanks!
- Nurit Haspel

**Comment by AdamFinkleUMB** [comment]
When we need the letters representing the sequences, a python package called pyfaidx efficiently and conveniently returns the string of letters representing any named protein sequence from a FASTA file.

When we just need to crunch numbers fast, the program could facilitate counting the times each letter appears in each column by implementing its own sequence database and converting the letters of every sequence in that database to numbers.  Then, it could return the numbers for each sequence, stack them into a 2-d array, and for each number in each column of the 2-d array, increment the counter at the corresponding index of a corresponding array.

Please tell me what you think of this idea.

**Comment by ozgunbabur** [comment]
You can use a FASTA reader if you like, but I advise against coding amino acids with numbers. It is an unnecessary complication. We don't need it.

Please make sure that you implement a class with a method that satisfies the below input and output requirements.
Inputs: Gene name, site location, window half-width
Output: The sequence as a string

For instance, the method call on (RTN4, S107, 5) should return "PERQPSWDPSP".

**Comment by ozgunbabur** [comment]
If you want to do it this way, then please don't forget to write converters between a string representation and a number array representation.

**Comment by ozgunbabur** [comment]
Adam, please add the test case given in this issue (RTN4 S107 window 5 expected to return PERQPSWDPSP). You will see it is not functioning correctly. Please use this example to fix the bug.

**Comment by ozgunbabur** [comment]
Seems working! But the last test in the test.py (windowed ranked sequence) prints different sequences for "expected" and "found". Please check.

**Comment by AdamFinkleUMB** [comment]
Ok, fixed.
