### ISSUE TITLE
Null distribution of p-values

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/Finkle-PHYS-479#13]
Our enrichment p-values are not uniformly distributed because of the threshold searching step. In that sense, they are not actually p-values but just scores. To estimate the nominal p-values (statistical significance) of these scores, we need to estimate the null distribution of the scores.

Write a method that will generate a null distribution of these enrichment and deficiency scores by randomizing the ranking of the given sequences, searching for enrichment and deficiency for each aa and each location, collecting the scores, and repeating this until there is a sufficient amount of random scores collected (something between 1000  and a million is ideal, make this a parameter).

Make sure this procedure uses the same parameters (step size, clumping, etc) as with the original calculations.

**Comment by AdamFinkleUMB** [comment]
Generating a random ranking takes about a second: generating even just 1,000 could take almost twenty minutes.

**Comment by ozgunbabur** [comment]
20 minutes does not sound awful. You can use n=10 during development. We can increase this to 1000 or higher when we get an actual run.

**Comment by AdamFinkleUMB** [comment]
How do you want the scores to be collected?  I could imagine a tuple

`
(
    # column
    ( # letter
        ( # scores
`

**Comment by ozgunbabur** [comment]
Just as a bunch of numbers.

**Comment by AdamFinkleUMB** [comment]
I'm not sure what you mean.  The distribution is of each letter at each column and would have to be organized as such, right?

**Comment by ozgunbabur** [comment]
There is a way, but not a short way. After generating the distribution, you can use it to estimate nominal p-values of the scores that you get from randomized sequences. If there are no bugs, we expect the distribution of the nominal p-values to be uniform.
