### ISSUE TITLE
Bug in test.py

### ISSUE THREAD

**Issue by nurith** [PathwayAndDataAnalysis/Finkle-PHYS-479#14]
Line 133, path variable is not defined. You gave it another name - path_file or something.

**Comment by AdamFinkleUMB** [comment]
Bug fixed!  The program runs now.

**Comment by ozgunbabur** [comment]
test.py gives me the below error:

  File "/home/ozgunbabur/Code/Finkle-PHYS-479/test.py", line 270
    print("\nMost Significant P Values Test\n") most_significant_p_values_test()
                                                ^
SyntaxError: invalid syntax

**Comment by AdamFinkleUMB** [comment]
Fixed it!
