### ISSUE TITLE
Hypergeometric test for enrichment test

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/Finkle-PHYS-479#2]
Write a script that will generate a p-value for enrichment (or for the opposite: deficiency), for a given set of values in a 2x2 table, using the hypergeometric test.

Step 1:  Find a library that will run the hypergeometric test on a given 2x2 table to generate a p-value.

Step 2: Implement a script that will use that library to calculate a p-value for the enrichment in a given 2x2 table.

Here is an example. Let's say we are given the below 2x2 table

|   | -  | +  |
|---|----|----|
| - | 15  | 10  |
| + | 3 | 5 |

And we want to check if the number 5 indicates an enrichment (i.e. 5 is too high assuming an independent distribution of these two features). Then the enrichment test will apply the hypergeometric test on this distribution and more imbalanced distributions. These are

|   | -  | +  |
|---|----|----|
| - | 15  | 10  |
| + | 3 | 5 |

|   | -  | +  |
|---|----|----|
| - | 16  | 9  |
| + | 2 | 6 |

|   | -  | +  |
|---|----|----|
| - | 17  | 8  |
| + | 1 | 7 |

|   | -  | +  |
|---|----|----|
| - | 18  | 7  |
| + | 0 | 8 |

The sum of p-values from hypergeometric tests of these distributions will give us the one-tailed p-value for enrichment. Here we found the probability of the +/+ case being 5 or more by random. 

To test for deficiency instead (to see if 5 is a significantly low number), we need to find the probability of the +/+ case being 5 or fewer by random. In that case, the distributions we need to include are

|   | -  | +  |
|---|----|----|
| - | 15  | 10  |
| + | 3 | 5 |

|   | -  | +  |
|---|----|----|
| - | 14  | 11  |
| + | 4 | 4 |

|   | -  | +  |
|---|----|----|
| - | 13  | 12  |
| + | 5 | 3 |

|   | -  | +  |
|---|----|----|
| - | 12  | 13  |
| + | 6 | 2 |

|   | -  | +  |
|---|----|----|
| - | 11  | 14  |
| + | 7 | 1 |

|   | -  | +  |
|---|----|----|
| - | 10  | 15  |
| + | 8 | 0 |

**Comment by nurith** [comment]
Ozgun,

I may have missed the original emails, can you please send a link to 
some info about enrichment tables? I'm not sure how to read them.

Thanks!
- Nurit Haspel

**Comment by ozgunbabur** [comment]
And please write tests to make sure your code works as expected. Here are some tables for testing.

Assume the letters a, b, c, and d represent the counts as displayed below.

|   | -  | +  |
|---|----|----|
| - | a  | b  |
| + | c | d |

Then if a = 4, b = 6, c = 6, d = 4, 
The enrichment p-value should be 0.9105522960012121
The deficiency p-value should be 0.3281408993483296

If a = 20, b = 30, c = 25, d = 30, 
The enrichment p-value should be 0.7766662300662146
The deficiency p-value should be 0.357198690677301

If a = 15, b = 8, c = 20, d = 42
The enrichment p-value should be 0.006445865568610187
The deficiency p-value should be 0.9985899806396821

If a = 21, b = 20, c = 34, d = 13
The enrichment p-value should be 0.9883420938210076
The deficiency p-value should be 0.0341612031176084

**Comment by AdamFinkleUMB** [comment]
Fixed it! It was a small error in the code.  Now, it passes 3 of 4 tests!

**Comment by ozgunbabur** [comment]
Almost there! There are a few problems. 

1. Please have 2 different methods: one for enrichment and one for deficiency. Instead of a "p_values" method, you can have an "enrichment_pval" and a "deficiency_pval" methods. We don't want these two p-values to be calculated together every time.
2. Your call of hypergeom.pmf for calculating the deficiency p-value puzzled me. This method takes these 4 parameters: (selected_favorable, trials, favorable, selected). And you use exactly this way for the enrichment p-values. But for deficiency p-value, you send "unfavorable" instead of favorable. Why is that?
3. The calculation of "more_favorable" and "less_favorable" arrays does not seem correct. The first array starts from selected_favorable and goes up to the max possible value. You assumed that max possible value is "favorable" but this is only sometimes true. If "selected" is smaller than "favorable", then it can only go up to "selected". In other words, the max possible value is min(selected, favorable). The calculation of "less_favorable" array is more problematic. This array should again start from "selected_favorable" and go down to the minimum possible value. That minimum possible value is max(0, selected + favorable - trials).

**Comment by AdamFinkleUMB** [comment]
I've applied your changes, and now the test passed only 3/4 of the enrichment tests and none of the deficiency ones, 3/4 of which it passed before.

**Comment by ozgunbabur** [comment]
There is a bug in the deficiency pval implementation. Please look at line 19.

**Comment by AdamFinkleUMB** [comment]
I feel silly.  The code seemed fine to me, so I sought errors in what I was trying to do, but then just ran the code and saw the return statement lacked a closing parenthesis.
________________________________
