### ISSUE TITLE
Write a README file and prepare some examples as test cases

### ISSUE THREAD

**Issue by nurith** [PathwayAndDataAnalysis/Finkle-PHYS-479#4]
Alternatively, you can open an "action" workflow.

**Comment by nurith** [comment]
A set of instructions inside a file : What is the thing, how to run and build a directory of test cases with expected results.

**Comment by nurith** [comment]
Thanks! But please also show a run example, like a specific command to run.

On 2022-04-07 19:42, AdamFinkleUMB wrote:
EXTERNAL SENDER

Closed #4<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPathwayAndDataAnalysis%2FFinkle-PHYS-479%2Fissues%2F4&data=04%7C01%7Cnurit.haspel%40umb.edu%7Cbeb7a2751b0149d7c8e008da18f04115%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637849717412687303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wtrWVNMxuZt5qKoHy9HLWDQpM572%2B19TTSHFOQTJTWM%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPathwayAndDataAnalysis%2FFinkle-PHYS-479%2Fissues%2F4%23event-6392636072&data=04%7C01%7Cnurit.haspel%40umb.edu%7Cbeb7a2751b0149d7c8e008da18f04115%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637849717412687303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hrjLugyq0aD%2BVWVVE4Ze61eieTDTc%2FuCeNhXU1bmbU0%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA2A7T3LXZRMM5GS4CTXZO3VD5XFVANCNFSM5S2BZMNA&data=04%7C01%7Cnurit.haspel%40umb.edu%7Cbeb7a2751b0149d7c8e008da18f04115%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637849717412687303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5rMw1RLIluxOUs%2FfiH8bvfiW4N1oNZW0%2BD1pCRYKLc0%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Thanks!
- Nurit Haspel

**Comment by AdamFinkleUMB** [comment]
Only one command to run so far--the test.  It's a module that you'd use while coding.

**Comment by ozgunbabur** [comment]
Adam, please see my previous comment about documenting the work that we need to do before running test.py.

**Comment by AdamFinkleUMB** [comment]
Alright, added it!

**Comment by ozgunbabur** [comment]
Hi Adam, where did you add it? I cannot see it in README.md.

**Comment by nurith** [comment]
Yeah, exactly.

On 2022-04-08 10:53, Özgün Babur wrote:
EXTERNAL SENDER

I think the README should mention that test.py is already running those tests.
But if I try to run test.py, I get errors. This README should guide us on how to successfully run test.py.
(create a "data" directory, download .fasta file in it, run build_database.py, etc)

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPathwayAndDataAnalysis%2FFinkle-PHYS-479%2Fissues%2F4%23issuecomment-1092951690&data=04%7C01%7Cnurit.haspel%40umb.edu%7C72caa3ca859b43f5bb3108da196f7ac9%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637850263839001560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0P%2B7liVxLLffmdopLmVWxocBlrMglulYlCP3huf7X3A%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA2A7T2GEOZNMJBOPXKAKMDVEBB4ZANCNFSM5S2BZMNA&data=04%7C01%7Cnurit.haspel%40umb.edu%7C72caa3ca859b43f5bb3108da196f7ac9%7Cb97188711ee94425953c1ace1373eb38%7C0%7C0%7C637850263839001560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uakFSRNiYJjcakbjPgA1mn%2BbJgCcAfsPYIb7JWVVzgE%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Thanks!
- Nurit Haspel
