### ISSUE TITLE
Use amino acid mapping to reduce the list of sequences

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/Finkle-PHYS-479#5]
I have added a new file to the project called amino-acid-mapping.tsv to the project. This is a 2-columns file where the first column is the original amino acid acid coming from the UniProt database and the second column is the mapped amino acid. For instance, we will map T to S because Threonine and Serine amino acids are very similar. They can be used interchangeably in the protein. We increase our statistical power by merging these amino acids in the analysis.

Please write a script that uses this mapping file to transform a given list of sequences. The method in the script will take a list of sequences as input and return an updated list of sequences where the 20 possible amino acids are reduced into 11.

Additionally, the analysis code should not assume any possible values for amino acids, but it should always look at what exists in the given list of sequences and compute accordingly.

**Comment by ozgunbabur** [comment]
Can you please also test the substitution method? You can test this case:

The input is a single sequence "ARNDCEQGHILKMFPSTWYV".
The expected output is "AKQDCDQAHIIKIFPSSWFI"

**Comment by AdamFinkleUMB** [comment]
Added!
