### ISSUE TITLE
Write a method that detects counts of amino acids in specific positions for a given list of ranked sequences

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/Finkle-PHYS-479#7]
To calculate enrichments, we need to decide for which amino acids we should run the test, and count their appearances. This issue is about creating that method.

Input: ranked sequences
Output: A dictionary of dictionaries that maps coordinates to dictionaries of amino acid counts.

For instance, for the below sequences

HDJSY
HDYST
KYHDH

we will have 5 different coordinates. The center is location 0. The coordinate increases as we go right, and decreases as we go left. So the list of coordinates from left to right is -2, -1, 0, 1, 2.

We want to find the counts of amino acids for each position. The required output for the above example is this:
{ -2: {"H": 2, "K": 1},
  -1: {"D": 2, "Y": 1},
   0: {"J": 1, "Y": 1, "H": 1},
   1: {"S": 2, "D": 1},
   2: {"Y": 1, "T": 1, "H": 1} }

**Comment by AdamFinkleUMB** [comment]
analysis.column_letter_counts returns a list of all counts of all letters in a column, indexed to the Unicode value of each letter.  analysis.letter_counts returns a nested list of all letter_column_counts in a list of windowed sequences.

**Comment by ozgunbabur** [comment]
Please write a test for each method you implemented and make sure the method works as expected.

**Comment by AdamFinkleUMB** [comment]
Test is written.  Sequences must be entered as columns, though.

**Comment by ozgunbabur** [comment]
test.py is giving an error. Please see
https://github.com/PathwayAndDataAnalysis/Finkle-PHYS-479/blob/main/test.py#L122

**Comment by AdamFinkleUMB** [comment]
Fixed.

**Comment by ozgunbabur** [comment]
Looks like all the tests about this method are failing:

"Letter Counts Test

Expected: H 2
Found: H 0

TEST FAILED!

Expected: K 1
Found: K 0

TEST FAILED!

..."

It goes on like that.

**Comment by AdamFinkleUMB** [comment]
Fixed the bug
